---
title: "Clase 6"
format: revealjs
editor: visual
---

6: 22-24

Clase No. 21 de 30. Apuntes de clase. Jordan Umaña 
Clase No. 21 de 30 
miércoles, 29 de marzo de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Jordan Umaña 
(Revisados por la profesora) 
Completar el Trabajo No. 2 y entregarlo antes del lunes 2 de abril a las 11:30 pm. (Evitar el golpe glotal) 
RECORDAR: Ver lista de símbolos fonéticos aquí (https://uncc.instructure.com/courses/44379/pages/simbolos­foneticos­para­copiar­y­pegar) . Alternancia Condicionada 
       [d]     Ejemplos:  ando, Don Pedro, caldo 
/d/ 
       [ð]     Ejemplos: lado, la dama 
Alternancia Libre 
Ejemplo: mismo 
        [s]    [mis­mo] 
 /s/   [z]    [miz­mo] Asimilación: la /s/ asimila la sonoridad de la vocal anterior y de la                       consonante posterior.         [h]    [mih­mo] 
        [ø]    [mi­mo]   Esta posibilidad se utiliza en el Caribe y las Islas Canarias 
En la palabra corazón, ¿se aplica lo que hemos descrito arriba? 
No se aplica lo que describimos arriba porque el sonido de la /s/ está entre dos vocales y no al final de una sílaba, es decir, en sílaba cerrada. NOTA: una sílaba cerrada es una sílaba que termina en consonante (ver FFE pp. 40­41). 
/r/  ­ [r] alveolar líquida (vibrante múltiple) sonora 
Ejemplos: roca [ró­ka] 
                 carro [ká­ro] 
                 calor [ka­lór] solo cuando queremos ser más exagerados (¡¡¡Qué calorrrrr!!!) 
/ɾ/ ­ [ɾ] alveolar líquida (vibrante simple) sonora 
Ejemplos: coro [kó­ro]  (Este sonido es similar a la “dd” en “ladder”) 
                 calor [ka­lóɾ] 
Práctica 
1. coro (choir) / corro (I run o circle/ring of people) 
2. coral (coral)/ corral (chicken coop) 
3. pero (but) / perro (dog) 
4. ahora (now) / ahorra (save) 
5. pera (pear) / perra (female dog)
https://uncc.instructure.com/courses/44379/pages/clase-no-21-de-30-apuntes-de-clase-jordan-umana?module_item_id=769530 1/2 
7/21/2018 Clase No. 21 de 30. Apuntes de clase. Jordan Umaña: 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
6. cero (zero) / cerro (hill) 
7. foro (forum) / forro (lining for clothing) 
Práctica de Transcripción Fonética 
enriquecerse 
[en­ri­ke­séɾ­se] 
*********
https://uncc.instructure.com/courses/44379/pages/clase-no-21-de-30-apuntes-de-clase-jordan-umana?module_item_id=769530 2/2 
7/21/2018 Clase No. 22 de 30. Apuntes de clase. Keiva McCullough (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
Clase No. 22 de 30. Apuntes de clase. Keiva McCullough (2a vez) 
Clase No. 22 de 30 
lunes, 3 de abril de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Keiva McCullough (2a vez) 
(Revisados por la profesora) 
RECORDAR: Ver lista de símbolos fonéticos aquí (https://uncc.instructure.com/courses/44379/pages/simbolos­foneticos­para­copiar­y­pegar) . enriquecerse 
[en­ri­ke­séɾ­se] 
regresar 
[re­ ɣɾe­sáɾ] 
restaurar 
[res­tau̯­ɾáɾ] 
en Rusia 
[en­rú­si̯a] 
alrededor 
[al­re­ðe­ðóɾ] 
somos ricos 
[só­mos­ri­kos] o [so­moz­ri­cos] o [somo­ri­cos] 
Israel 
[is­ra­él] o [iz­ra­él] o [i­ra­él] 
Aurelia es una chica muy capaz 
[au̯­ɾé­li̯a­é­su­na­tʃí­ka­mui̯­ka­pás] o  
[au̯­ɾé­li̯a­é­su­na­tʃí­ka­mui̯­ka­páθ] (para el 5% de hispanohablantes, los que viven en la mitad norte de España) Modo de Articulación: Nasales 
El aire sale por la nariz cuando se pronuncian las consonantes nasales. 
[m] bilabial nasal sonora 
/m/ ­ [m] malo [má­lo] amar [a­máɾ] álbum [ál­βum]
https://uncc.instructure.com/courses/44379/pages/clase-no-22-de-30-apuntes-de-clase-keiva-mccullough-2a-vez?module_item_id=769531 1/2 
7/21/2018 Clase No. 23 de 30. Apuntes de clase. David Cortés (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
Clase No. 23 de 30. Apuntes de clase. David Cortés (2a vez) 
Clase No. 23 de 30 
miércoles, 5 de abril de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de David Cortés (2a vez) 
(Revisados por la profesora) 
Recordatorio: Mirar instrucciones del trabajo número 3 (https://uncc.instructure.com/courses/44379/pages/trabajo­no­3­de­5­instrucciones primavera­2017) , que debemos completar antes del 04/17 a las 11.30pm.  
RECORDAR: Ver lista de símbolos fonéticos aquí (https://uncc.instructure.com/courses/44379/pages/simbolos­foneticos­para­copiar­y­pegar) . Nasales 
/n/ ­ [n] ­ nasal, alveolar, sonora ­ ene neutra ­> no, nadar, mano. 
     ­ [ɱ] ­ nasal labiodental, sonora ­ ene antes de [f] ­> informar, ánfora. 
     ­ [n̪] ­ nasal, dental, sonora ­ ene antes de dental (/t/ o /d/) ­> tanto, andar. 
     ­ [ɳ] ­ nasal, alveopalatal, sonora ­ ene antes de /tʃ/ y /ll/ ­> ancho, son llanas.  
     ­ [ɲ] ­ nasal, palatal, sonora ­ ene antes del sonido [ ʝ ] ­> con hierbas. Palabras con ñ.  
     ­ [ŋ] ­ nasal, velar, sonora ­ ene antes de velar (/k/, /g/) ­> tengo, cinco.  
     ­ [m] ­ nasal bilabial, sonora ­ antes de [m] ­> conmigo. 
Africadas: 
/tʃ/ ­[tʃ] africada, alveopalatal, sorda ­ sonido de "ch" ­> leche, coche. 
Práctica 
1. Los perros atacaron al niño 
[los­pé­ro­sa­ta­ká­ɾo­nal­ní­ɲo] 
NOTA: La clase terminó aquí. Las transcripciones de las oraciones 2 a 5 se comentarán en la próxima clase. 
2. Ojalá que venga con Amelia. 
3. ¿Y cuántos niños tiene usted? 
4. Todos están conmigo. 
5. Sus amigos murieron muy jóvenes. 
************
https://uncc.instructure.com/courses/44379/pages/clase-no-23-de-30-apuntes-de-clase-david-cortes-2a-vez?module_item_id=772312 1/1 
7/21/2018 Clase No. 24 de 30. Apuntes de clase. Raven Sutton (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
Clase No. 24 de 30. Apuntes de clase. Raven Suon (2a vez) 
Clase No. 24 de 30 
lunes, 10 de abril de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Raven Sutton (2a vez) 
(Revisados por la profesora) 
Repaso de instrucciones de trabajo no. 3 (https://uncc.instructure.com/courses/44379/pages/trabajo­no­3­de­5­instrucciones­primavera­2017) para 4/17/2017 
RECORDAR: Ver lista de símbolos fonéticos aquí (https://uncc.instructure.com/courses/44379/pages/simbolos­foneticos­para­copiar­y­pegar) . Práctica de trabajo no. 3 
Marca las áreas donde se tiene que controlar el golpe (u oclusión) glotal  
Cuando hay 2 vocales contiguas (una a final de palabra y otra a pioncipio de palabra)  o cuando hay una consonante a final de palabra y una vocal al principio de la palabra siguiente. 
1. Pito Pérez puso el papel en el pupitre 
2. Pídele a Paco un poco de pan. 
3. ¿Puedes poner el programa para el público? 
4. Mi tío Teodoro tiene tantos tipos de trajes como tú. 
5. Noto que tú tienes apetito fuerte, Tomás. 
6. Carlos comió cacahuetes calientes en la calle 
7. Caminó cuarenta kilómetros. 
8. Los toros de Pamplona son famosos 
9. El es bajo, rechoncho y fuerte 
[Continuación de transcripción fonética de la clase previa] 
1. Los perros atacaron al niño 
[los – pé – ro – sa – ta – ká ­ ɾo – nal – ní – ɲo] 
2. Ojalá que venga con Amelia 
[o – xa – lá – ke – βéŋ – ga – ko – na – mé – li̯a] 
[o – ha – lá – ke – βéŋ – ga – ko – na – mé – li̯a] 
3. ¿Y cuántos niños tiene usted? 
[i – ku̯án̪ – tos – ní ­ ɲos – ti̯é – neu̯s – téð] 
[i – ku̯án̪ – tos – ní ­ ɲos – ti̯é – neu̯s – téd] 
[i – ku̯án̪ – tos – ní ­ ɲos – ti̯é – neu̯s – téø] NOTA: [ø] indica ausencia de sonido. 
4. Todos están conmigo* 
[tó – ðo – ses – táŋ – kom – mí ­ ɣo] 
5. Sus amigos murieron muy jóvenes*
https://uncc.instructure.com/courses/44379/pages/clase-no-24-de-30-apuntes-de-clase-raven-sutton-2a-vez?module_item_id=772313 1/2 
7/21/2018 Clase No. 24 de 30. Apuntes de clase. Raven Sutton (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
[su – sa – mí ­ ɣos – mu ­ ɾi̯e ­ ɾom – mu̯i – xó – βe –nes] 
[su – sa – mí ­ ɣoz – mu ­ ɾi̯e ­ ɾom – mu̯i – hó – βe –nes] 
*NOTA: cuando la /n/ está seguida de la /m/, se convierte en [m]. **************
https://uncc.instructure.com/courses/44379/pages/clase-no-24-de-30-apuntes-de-clase-raven-sutton-2a-vez?module_item_id=772313 2/2 
7/21/2018 Clase No. 25 de 30. Apuntes de clase. Caitlin Harrison (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001
