---
title: "Clase 4"
format: revealjs
editor: visual
---

13-17

Clase No. 13 de 30. Apuntes de clase. Stephanie Marek Clase No. 13 de 30 miércoles, 21 de febrero de 2017 SPAN 4231 / 5050: Introducción a la fonética española

Empezamos la clase con un repaso breve: una sílaba es una secuencia de sonidos que se pronuncia en un solo golpe de voz. Una palabra puede constar de una o más de una sílaba. En cualquier caso el núcleo silábico es la vocal, es decir que sin vocal no hay sílaba. Términos nuevos: Sílaba abierta La mayoría de las sílabas son abiertas Es una sílaba que termina en vocal pa/la/bra Sílaba cerrada Termina en consonante Vo/cal ¿Cómo sabemos qué sonidos incluir en una sílaba? 1. Una sílaba sólo puede empezar con una vocal o con una consonante o grupo consonántico (tr,cr,br,cl,fl,fr) que pueda estar en el principio de una palabra. Práctica 1. Des/de 2. cons/ta/tar Observen que no agrupamos "sta" porque no hay palabras que empiecen con "st". Esta es la razón por la que los hispanohablantes tienen dificultades con "stop", "street" , y "start", a las que añaden "e" al principio. 1. ac/ción 2. a/ten/ción 2. Una consonante que está entre dos vocales o entre una vocal y un diptongo o entre un diptongo y una vocal siempre se agrupa con la vocal o el diptongo que la sigue (el que está a la derecha) ­\> au/ri/cu/lar ­\> a/sien/to Hicimos más práctica: 1. a/la 2. a/la/ba/ma 3. co/he/te 4. al/mo/ha/da 5. frac/ción 6. ins/ti/tu/ción 7. cons/pi/ra/ción 8. se/guir 9. bi/lin/güe 10. pa/que/te 11. ca/lle 12. se/rra/no 13. mu/cha/cho https://uncc.instructure.com/courses/44379/pages/clase-no-13-de-30-apuntes-de-clase-stephanie-marek?module_item_id=751944 1/2 7/21/2018 Clase No. 13 de 30. Apuntes de clase. Stephanie Marek: 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined Un nota importante es que hay que evitar el golpe glotal \[ʔ\] entre vocales tanto dentro de las palabras como dentro de las frases y oraciones. \*\*\*\*\*\*\*\*\*\*\*\* https://uncc.instructure.com/courses/44379/pages/clase-no-13-de-30-apuntes-de-clase-stephanie-marek?module_item_id=751944 2/2 7/21/2018 Clase No. 14 de 30. Apuntes de clase. Arianna Martínez: 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined Clase No. 14 de 30. Apuntes de clase. Arianna Marnez Clase No. 14 de 30 lunes, 27 de febrero de 2017 SPAN 4231 / 5050: Introducción a la fonética española Apuntes de Arianna Martínez (Revisados por la profesora) Al empezar la clase comenzamos con el repaso de la página de la tarea y el plan diario (https://uncc.instructure.com/courses/44379/pages/plan diario­y­tareas­primavera­2017) .\
Continuamos la práctica de evitar el golpe glotal \[ʔ\]\
Preactica: El hombre y el oso cuanto más feo más hermoso.\
Dividir las silabas de esta frase:\
\[e­lóm­bre­ye­lo­só­cuan­to­mas­fé­o­ma­ser­mó­so\]\
Diptongo: ¿Cuáles son las características del diptongo?\
1. Dos vocales.\
2. Una vocal fuerte (a,e,o).\
3. Una vocal débil (i,u)\
Nota: Dos vocales débiles también pueden formar diptongo.\
Ej: Ruido\
4. Las dos vocales se pronuncian en una sola sílaba.\
Ejemplos:\
­cautela\
­suegro\
­cohibir\
­viejo\
­puente\
Triptongo:\
Vocal débil+ vocal fuerte+ vocal débil\
Ej: miau, buey, limpiáis (forma vosotros).\
Hiato: ­Dos vocales contiguas (una al lado de la otra).\
­Estas dos vocales se pronuncian en sílabas separadas.\
Ej: cohete, almohada, Maria, héroe, poeta, púa.\
­Estas vocales son fuertes (a,e,o).\
­Son vocales cuyo diptongo potencial está roto.\
Ej: María, púa ­Pueden ser vocales dobles Ej: zoológico, cooperación, leer\
https://uncc.instructure.com/courses/44379/pages/clase-no-14-de-30-apuntes-de-clase-arianna-martinez?module_item_id=751947 1/2 7/21/2018 Clase No. 14 de 30. Apuntes de clase. Arianna Martínez: 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined Grupo Fónico:\
Es el conjunto de sonidos lingüísticos (consonantes y vocales) que se pronuncian entre dos pausas. Ej: El hombre y el oso cuanto más feo más hermoso.\
El Enlace: El fenómeno por el cual el sonido final de una palabra se une fonéticamente al sonido inicial de la siguiente palabra. Ej: El hombre y el oso cuanto más feo mas hermoso.\
A buena hambre no hay pan duro.\
\*\*\*\*\*\*\*\*\* https://uncc.instructure.com/courses/44379/pages/clase-no-14-de-30-apuntes-de-clase-arianna-martinez?module_item_id=751947 2/2 7/21/2018 Clase No. 15 de 30. Apuntes de clase. Keiva McCullough: 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined Clase No. 15 de 30. Apuntes de clase. Keiva McCullough Clase No. 15 de 30 miércoles, 1 de marzo de 2017 SPAN 4231 / 5050: Introducción a la fonética española Apuntes de Keiva McCullough (Revisados por la profesora) A buena hambre no hay pan duro. \[a­bu̯e­na­am­bre­no­ai̯­pan­du­ro\] En boca cerrada no entran moscas \[en­bo­ca­ce­rra­da­no­en­tran­mos­cas\] El grupo fónico y las transformaciones vocálicas Las transformaciones vocálicas dentro del grupo fónico dependen de tres factores. 1. Estilo de habla (rápido o lento) 2. Acento prosódico 3. El tipo de vocal Transformación #1 Diptongación o triptongación Hablé ingles \[a­bléi̯n­glés\] estudió historia \[es­tu­di̯ói̯s­to­ri̯a\] Transformación #2 Eliminación de la vocal en ciertos contextos La avisé \[la­vi­sé\] va a salir \[va­sa­lír\] \[­e\] en una palabra monosílaba y átona me imagino lento \[mei̯­ma­gí­no\] rápido \[mi­ma­gí­no\] Transformación #3 cambio cualitativo No entró \[nu̯en­tró\] \[i\] entre vocales se pronuncia \[ʝ \] dicho y hecho \[di­cho­ʝe­cho\] Practicar transcripción semi­fonética La insistencia logra el éxito universitario. \[lai̯n­sis­tén­ci̯a­ló­gra­(e)­lé­xi­tou̯­ni­ver­si­ta­ri̯o\] https://uncc.instructure.com/courses/44379/pages/clase-no-15-de-30-apuntes-de-clase-keiva-mccullough?module_item_id=751946 1/2 7/21/2018 Clase No. 16 de 30. Apuntes de clase. Adrien Roberson: 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined Clase No. 16 de 30. Apuntes de clase. Adrien Roberson Clase No. 16 de 30 lunes, 13 de marzo de 2017 SPAN 4231 / 5050: Introducción a la fonética española Apuntes de Adrien Roberson (Revisados por la profesora) ¿Qué diferencias observan entre los sonidos vocálicos y los sonidos consonánticos? 1. Las vocales no experimentan obstrucción en la salida del aire. 2. Las vocales son siempre el núcleo silábico y por tanto una vocal puede ser una sílaba. Criterios para describir una consonante 1. El lugar de articulación, es decir dónde, dentro del aparato fonador, ocurre principalmente la pronunciación del sonido. 2. El modo de articulación describe qué tipo de obstrucción experimenta el aire en el proceso de pronunciación. 3. Sonoridad a ausencia de sonoridad. Estas dos características dependen de las cuerdas vocales. Si las cuerdas vocales vibran, hacemos una consonante sonora y si no vibran, hacemos una consonante sorda. Lugar de articulation (bilabial, dental, velar) Modo de articulacion (oclusiva, fricativa) sorda (voiceless) sonora (voiced) Ver diagrama semimudo del aparato fonador (https://uncc.instructure.com/courses/44379/files/1217466/download?wrap=1) (https://uncc.instructure.com/courses/44379/files/1217466/download?wrap=1) .\
Ver símbolos fonéticos para copiar y pegar (https://uncc.instructure.com/courses/44379/pages/s­percent­c3­percent­admbolos­fon­percent­c3­ percent­a9ticos­para­copiar­y­pegar) . Descripción de consonantes específicas /p/ ­­­\> \[p\] bilabial, oclusiva, sorda Evitar el "puff" de la \[p\], especialmente en la sílaba tónica (la que lleva el acento prosódico) /t/ ­­­\> \[t\] dental, oclusiva, sorda Evitar el "puff" de la \[t\], especialmente en la sílaba tónica; evitar poner la lengua en los alveolos. /k/ ­­­\> \[k\] velar, oclusiva, sorda Evitar el "puff", especialmente en la sílaba tónica.\
Práctica Paco compró cocos con poca plata. Timoteo tiene tomates. /b/ ­­­\> \[b\] bilabial, oclusiva, sonora /b/ ­­­\> \[\] bilabial, fricativa, sonora \[b\] bola, ambos; este alófono ocurre en posición inicial absoluta, es decir, al principio de un grupo fónico y después de /n/ y /m/. https://uncc.instructure.com/courses/44379/pages/clase-no-16-de-30-apuntes-de-clase-adrien-roberson?module_item_id=751945 1/2 7/21/2018

Clase No. 16 de 30. Apuntes de clase. Adrien Roberson: 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined \[\] lavar, lobo, la vaca, la bola; este alófono ocurre entre vocales, tanto dentro de una palabra como entre paClase No. 16 de 30. Apuntes de clase. Adrien Roberson 
Clase No. 16 de 30 
lunes, 13 de marzo de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Adrien Roberson 
(Revisados por la profesora) 
¿Qué diferencias observan entre los sonidos vocálicos y los sonidos consonánticos? 
1. Las vocales no experimentan obstrucción en la salida del aire. 
2. Las vocales son siempre el núcleo silábico y por tanto una vocal puede ser una sílaba. 
Criterios para describir una consonante 
1. El lugar de articulación, es decir dónde, dentro del aparato fonador, ocurre principalmente la pronunciación del sonido.  2. El modo de articulación describe qué tipo de obstrucción experimenta el aire en el proceso de pronunciación. 
3. Sonoridad a ausencia de sonoridad. Estas dos características dependen de las cuerdas vocales. Si las cuerdas vocales vibran, hacemos una consonante sonora y si no vibran, hacemos una consonante sorda. 
Lugar de articulation (bilabial, dental, velar) 
Modo de articulacion (oclusiva, fricativa) 
sorda (voiceless) 
sonora (voiced) 
Ver diagrama semimudo del aparato fonador (https://uncc.instructure.com/courses/44379/files/1217466/download?wrap=1) (https://uncc.instructure.com/courses/44379/files/1217466/download?wrap=1) .  
Ver símbolos fonéticos para copiar y pegar (https://uncc.instructure.com/courses/44379/pages/s­percent­c3­percent­admbolos­fon­percent­c3­ percent­a9ticos­para­copiar­y­pegar) . 
Descripción de consonantes específicas 
/p/ ­­­> [p] bilabial, oclusiva, sorda 
Evitar el "puff" de la [p], especialmente en la sílaba tónica (la que lleva el acento prosódico) 
/t/ ­­­> [t] dental, oclusiva, sorda 
Evitar el "puff" de la [t], especialmente en la sílaba tónica; evitar poner la lengua en los alveolos. 
/k/ ­­­> [k] velar, oclusiva, sorda 
Evitar el "puff", especialmente en la sílaba tónica.  
Práctica 
Paco compró cocos con poca plata. 
Timoteo tiene tomates. 
/b/ ­­­> [b] bilabial, oclusiva, sonora 
/b/ ­­­> [] bilabial, fricativa, sonora 
[b] bola, ambos; este alófono ocurre en posición inicial absoluta, es decir, al principio de un grupo fónico y después de /n/ y /m/. 
https://uncc.instructure.com/courses/44379/pages/clase-no-16-de-30-apuntes-de-clase-adrien-roberson?module_item_id=751945 1/2 
7/21/2018 Clase No. 16 de 30. Apuntes de clase. Adrien Roberson: 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
[] lavar, lobo, la vaca, la bola; este alófono ocurre entre vocales, tanto dentro de una palabra como entre palabras. ************
https://uncc.instru
labras. \*\*\*\*\*\*\*\*\*\*\*\* https://uncc.instructure.com/courses/44379/pages/clase-no-16-de-30-apuntes-de-clase-adrien-roberson?module_item_id=751945 2/2 7/21/2018 Clase No. 17 de 30. Apuntes de clase. Raven Sutton: 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001\_


