---
title: "Clase 8"
format: revealjs
editor: visual
---
Clase No. 28 de 30. Apuntes de clase. Samantha Creasy (2a vez) 
Clase No. 28 de 30 
lunes, 24 de abril de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Samantha Creasy (2a vez) 
(Revisados por la profesora) 
Revisamos el Plan diario (https://uncc.instructure.com/courses/44379/pages/plan­diario­y­tareas­primavera­2017) y Trabajo 5 (https://uncc.instructure.com/courses/44379/pages/trabajo­no­5­de­5­instrucciones­primavera­2017) . 
**Recordar completar elvaluaciones (http://%5Bhttps://uncc.campuslabs.com/courseeval/)  de las clases** 
Autoprueba 
Fase 1a Reflexión individual 
Fase 2a Reflexión con el companero 
Fase 3a Reflexión de toda la clase (Puesta en común) 
1. ¿De qué fonemas es [ɲ] alófono? 
/n/ ­ [ɲ] con hierbas, estan llenos (/n/ antes de consonante palatal) 
/ɲ/   ­[ɲ]  niño, sueño 
2. ¿De qué fonemas es [m] alófono? 
/m/ ­ [m] somos 
/n/ ­ [m] son buenos, conmigo   (/n/ antes consonante bilabial) 
3. ¿De qué fonemas es [ʝ] alófono? 
/i/ ­  [ʝ]  hielo, hierba  (/i/ antes de /e/ a principio de palabra) 
/ʝ/ ­ [ʝ]  calle, yo 
Práctica. Pasar de transcripción fonética a representación ortográfica 
1. [eɱ­fɾén̪­te­ðel­kom­bén̪­to­ðe­sam­be­ní­to­a­βí­au̯ŋ­wéɾ 
­to­ʝé­no­ðe­na­ɾáŋ­xos] 
 En frente del convento de San Benito había un huerto lleno de naranjos. 
2. Explicar las dificultades fonéticas que un anglohablante podría encontrar al pronunciar esta oración. Vamos a enfocarnos en las palreas No. 1 a 5. 
1. En 2. frente 3. del  4. convento 5. de 6. San 7. Benito 8. había 9. un 10. huerto 11. lleno 12. de 13. naranjos 
No. 4. La "v" de convento debe pronunciarse [b]. El sonido [v] no existe en el 95% de los dialectos del español. *************
https://uncc.instructure.com/courses/44379/pages/clase-no-28-de-30-apuntes-de-clase-samantha-creasy-2a-vez?module_item_id=785743 1/1 
7/21/2018 Clase No. 29 de 30. Apuntes de clase. Stephanie Marek (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
Clase No. 29 de 30. Apuntes de clase. Stephanie Marek (2a vez) 
Clase No. 29 de 30 
miércoles, 26 de abril de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Stephanie Marek (2a vez) 
(Revisados por la profesora) 
                          
Primero, pasamos tiempo trabajando con trabajo #5 (https://uncc.instructure.com/courses/44379/pages/trabajo­no­5­de­5­instrucciones­primavera 2017) 
Luego, pasamos tiempo trabajando con la Recitación de La Higuera (https://uncc.instructure.com/courses/44379/pages/recitacion­la­higuera instrucciones­primavera­2017) , para el 6 de mayo. 
1. Porque_es_áspera_y fea 
2. Porque todas_sus ramas_son grises 
3. Yo le tengo piedad_a la_higuera 
4. En mi quinta_hay cien_ árboles 
Luego trabajamos con el guía de estudio para le examen final (https://uncc.instructure.com/courses/44379/pages/guia­de­estudio­para­el­examen final­primavera­2017) . 
#5 Comparando el inglés con el español, explica el estatus fonológico de los fonos [s] y [z] en estas dos lenguas. Ilustra tu explicación con ejemplos 
/s/ ­ [s]: alveolar, fricativa sorda.  Ej: solo/más/mismo 
          ­ [z]: alveolar, fricativa sonora. Ej: mismo [míz­mo] NOTA: muchos hablantes pronuncian [z] antes de consonante sonora, pero esta pronunciación es opcional. 
** Repasa clases 21 & 26 para la nociones de alternancia libre y alternancia condicionada. Ver también FFE p. 220 y 221. 
El espanol usar [s] o [z] es opcional (alternancia libre) cuando /s/ ocurre antes de consonante sonora. 
    En inglés 
    [s] ­ [s]        sip, precedent 
    [z] ­ [z]        zip, president 
Identificar área de dificultad fonética para los anglohablantes 
En frente del convento de San Benito había un huerto lleno naranjos 
   1    2    3  4      5   6    7    8 
[eɱ­frén̪­te­ðel­kom­bén̪­to­ðe]   
Problemas que podría occuir en la pronunciación 
#4 Controlar el golpe glotal. 
#6 Evitar el sonido [v], que no existe en español.
https://uncc.instructure.com/courses/44379/pages/clase-no-29-de-30-apuntes-de-clase-stephanie-marek-2a-vez?module_item_id=785744 1/2 
7/21/2018 Clase No. 29 de 30. Apuntes de clase. Stephanie Marek (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
#8 La ‘d’ suave [ð] (fricativa interdental sonora). Este sonido es difícil porque no existe como sonido de alternancia variable del fonema /d/ y además el fonema /d/ inglés en posición intervocálica generalmente es un sonido alveolar, es decir que la punta de la lengua se coloca en el área de los alvéolos. 
************
https://uncc.instructure.com/courses/44379/pages/clase-no-29-de-30-apuntes-de-clase-stephanie-marek-2a-vez?module_item_id=785744 2/2 
7/21/2018 Clase No. 30 de 30. Apuntes de clase. Adrien Roberson y Alex Bierrenbach (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
Clase No. 30 de 30. Apuntes de clase. Adrien Roberson y Alex Bierrenbach (2a vez) 
Clase No. 30 de 30 
lunes, 1 de mayo de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Adrien Roberson (2a vez) y Alex Bierrenbach (2a vez) 
(Revisados por la profesora) 
Repasamos las Instrucciones de la Recitación del poema "La higuera" (https://uncc.instructure.com/courses/44379/pages/recitacion­la­higuera instrucciones­primavera­2017) .       
Repasamos la Guía de estudio para el examen final (https://uncc.instructure.com/courses/44379/pages/guia­de­estudio­para­el­examen­final primavera­2017) .  
[¡¡ATENCIÓN!!: Terminamos de comentar las dificultades fonéticas potenciales de "En frente del convento de San Benito había un huerto lleno de naranjos". El borrador de los apuntes no contiene información sobre esta parte de la clase. Si algún compañero/a tiene esta información, que la añada a los apuntes de Adrien en Apuntes de clase. Borradores (https://uncc.instructure.com/courses/44379/discussion_topics/77056)  haciendo un "reply" a la entrada (entry) de Adrien.] 
En Puerto Rico conviene llamar "nenes" a los niños porque los boricuas mismos los llaman así. 
P­ evitar el puff 
ue­ no romper el diptongo 
r­ suave 
t­ Evitar el puff, poner la lengua en los dientes 
R­ fuerte necesitas vibrar la lengua 
c­ evitar el puff 
v­ hay que pronunciar como [b] 
ie­ no romper el diptongo 
ll­ tiene el sonido [ʝ] nunca tiene el sonido de [l] 
ua­ no romper el diptongo 
n_a­ no hacer el golpe glotal 
Transcribir fonéticamente  
[em­pu̯éɾ­to­rí­ko­kom­bi̯é­ne­ʝa­máɾ­né­ne­sa­los­ní­ɲos­poɾ­ke­los­bo­ɾí­ku̯as­mís­mos­los­ʝá­ma­na­sí] 
[em­pu̯éɾ­to­rí­ko­kom­bi̯é­ne­ʝa­máɾ­né­ne­sa­loz­ní­ɲos­poɾ­ke­loz­βo­ɾí­ku̯as­míz­moz­los­ʝá­ma­na­sí] 
***********
https://uncc.instructure.com/courses/44379/pages/clase-no-30-de-30-apuntes-de-clase-adrien-roberson-y-alex-bierrenbach-2a-vez?module_item_id=785745 1/1 
