---
title: "Introducción a la fonética española: Semana 1"
format: revealjs
editor: source
incremental: true 
---

# Intro

-   Soy Kyle
    -   email

------------------------------------------------------------------------

# Intro

Quienes son uds

------------------------------------------------------------------------

# Libro opcional

Schwegler, A., Kempff, J., Ameal ­Guerra, A. (2009). Fonética y fonología españolas. Hoboken, NJ: John Wiley & Sons. 4a. (ISBN 9780470421925)

------------------------------------------------------------------------

# Horario

No tenemos clase...

------------------------------------------------------------------------

# RAE (Real Academia Española)

-   La institución visible asociada con la lengua española. Comunica cómo usar la lengua y la forma aceptable para que todos la usen en una manera uniforme. Puedes usar el sitio web de la RAE como diccionario y para consulta de temas gramaticales

-   www.rae.es

------------------------------------------------------------------------

# En grupos...

-   Es necesario la RAE? Porque, o porque no?

-   Si no existiera la RAE, que pasaría con la lengua española?

------------------------------------------------------------------------

Explica los conceptos marcados en negrita en la siguiente definición:

Una lengua es una forma de **comportamiento social (1)** que permite la comunicación mediante **el empleo creativo (2)** de un **sistema ordenado (3)** de **signos orales (4) arbitrarios (5)**.

------------------------------------------------------------------------

1.  comportamiento social

La lengua es el resultado de la interacción dentro de una comunidad.

Sin otro ser humano es impensable, y posiblemente imposible, crear una lengua.

La lengua es el resultado de un consenso dentro de una comunidad.

------------------------------------------------------------------------

2.  permite la comunicación mediante el empleo creativo

Una misma idea puede expresarse de varias formas diferentes.

Vemos creatividad en la combinación de sonidos lingüísticos cuando comparamos diferentes lenguas.

El léxico es un área de mucha creatividad ya que continuamente se crean palabras nuevas en cualquier lengua.

------------------------------------------------------------------------

3.  sistema ordenado

Es un sistema ordenado porque está regulado por normas gramaticales que todos los hablantes están de acuerdo en usar.

------------------------------------------------------------------------

4.  signos orales

La definición de signo es: una representación visual, auditiva o táctil que representa alguna otra cosa y que ha estado consesuado, no hay ningún tipo de relación natural entre el signo y el concepto o cosa representados por el signo.

La lengua no es el único lugar en el que encontramos signos, también podemos encontrarlos en los saludos (decir hola o adiós con la mano, o las señales de los coches/carros, por ejemplo).

Decimos que la lengua se forma de un sistema ordenado de signos orales, ya que la lengua se aprende mediante la oralidad y es esta la parte esencial de una lengua. Hay lenguas que no tienen escritura, solo oralidad y, aun así, las seguimos considerando lenguas y cumplen su función comunicativa dentro de la comunidad de hablantes.

------------------------------------------------------------------------

5.  Signos arbitrarios

Podemos decir que los signos que forman una lengua son arbitrarios, ya que estos no tienen ningún tipo de relación con su significado. Es decir, en la lengua no hay razón ni relación natural que pueda justificar los signos usados para nombrar objetos o conceptos.

¿Cuál es la prueba evidente de que las lenguas son conjuntos de signos arbitrarios? Que en el mundo hay más de 6000 lenguas. Así pues, la comunidad de hablantes, de forma arbitraria (ya que no hay una conexión lógica o natural entre signo y cosa o concepto representados), decide asociar un signo específico con una cosa o concepto específicos.

------------------------------------------------------------------------

EL OBJETIVO DE ESTA ASIGNATURA

-   El objetivo de esta clase es analizar la lengua española en su forma oral.

------------------------------------------------------------------------

ELEMENTOS SEGMENTALES DE UNA LENGUA:

-   sonidos vocálicos
-   sonidos consonánticos

------------------------------------------------------------------------

ELEMENTOS SUPRASEGMENTALES DE UNA LENGUA:

-   Los elementos suprasegmentales son las características fonéticas que incluyen 1) el acento prosódico, 2) la entonación y 3) el ritmo (ver FFE p.317).

-   NOTA: Sinónimos del término acento prosódico: acento fonético, acento tónico, acento primario, acento expiratorio, acento de intensidad (ver FFE p. 7).

------------------------------------------------------------------------

El acento prosódico

Decimos que una sílaba tiene el acento prosódico de una palabra cuando esa sílaba se pronuncia con especial énfasis.

------------------------------------------------------------------------

PRAAT!

------------------------------------------------------------------------

¿Cómo funciona el acento prosódico?

1­ Las palabras que terminan en vocal, en ­n o en ­s, tienden a tener el acento prosódico en la penúltima sílaba. Ejemplos: mesero, somos, caminan...

2­ Las palabras que terminan en sonido consonántico que no es ­n ni ­s, tienden a tener el acento prosódico en la última sílaba. Ejemplos: caminar, formal, tapiz.

------------------------------------------------------------------------
