---
title: "Clase 6"
format: revealjs
editor: visual
---

7: 25-27

Clase No. 25 de 30. Apuntes de clase. Caitlin Harrison (2a vez) 
Clase No. 25 de 30 
miércoles, 12 de abril de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Caitlin Harrison (2a vez) 
(Revisados por la profesora) 
RECORDAR: Ver lista de símbolos fonéticos aquí (https://uncc.instructure.com/courses/44379/pages/simbolos­foneticos­para­copiar­y­pegar) . /l/ ­ [l] alveolar, lateral, sonora 
           ­ ej. loco, cola, fatal  
           ­ Hay que controlar que la [l] no salga velar 
     ­ [l̪] dental, lateral, sonora 
           ­ aparece antes de las consonantes dentales 
           ­ ej. alto, sueldo 
    ­ [ʎ] palatal, lateral, sonora 
           ­ aparece antes de las consonantes palatales 
           ­ ej. al llamar 
Miramos los dos cuadros que aparecen al principio de nuestro libro y respondimos la pregunta: 
     Explicar de qué forma estos dos cuadros son diferentes y por qué. 
     ­Porque uno de ellos es un cuadro para los alófonos del español, y el otro es para los fonemas. Observen que el número de alófonos es mayor que el número de fonemas (o familias) 
Hicimos una práctica con la transcripción fonética. 
     [e­sú­na­kal­ku­la­ðó­ɾa­ði­xi­tál] ­ Es una calculadora digital 
     [ó­tʃu̯a­mí­ɣos­se­fu̯é­ɾo­nal­kám­po] ­ Ocho amigos se fueron al campo 
     [miz­ðú­ða­sí­ɣen­si̯én̪­do­laz­míz­mas] ­ Mis dudas siguen siendo las mismas 
Empezamos una transcripción fonética de la siguiente frase: 
     Él se refiere a un lugar donde un río negro se encuentra en confluencia con el ancho mar. 
****************
https://uncc.instructure.com/courses/44379/pages/clase-no-25-de-30-apuntes-de-clase-caitlin-harrison-2a-vez?module_item_id=774924 1/1 
7/21/2018 Clase No. 26 de 30. Apuntes de clase. Kiarra Balom (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
Clase No. 26 de 30. Apuntes de clase. Kiarra Balom (2a vez) 
Clase No. 26 de 30 
lunes, 17 de abril de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Kiarra Balom (2a vez) 
(Revisados por la profesora) 
RECORDAR 1: Ver lista de símbolos fonéticos aquí (https://uncc.instructure.com/courses/44379/pages/simbolos­foneticos­para­copiar­y­pegar) . 
RECORDAR 2: Ver aquí cuadro de alófonos completado en clase (https://uncc.instructure.com/courses/44379/files/1729910/download?wrap=1) (https://uncc.instructure.com/courses/44379/files/1729910/download?wrap=1) . 
/f/­ [f] labiodental fricativa sorda 
farmacia [far­má­si̯a]; o [far­má­θi̯a] (para el 5% de hispanohablantes, los de la mitad norte de España) 
/s/­ [s] alveolar fricativa sorda 
[z] opcional alveolar fricative Sonora 
mismo [miz­mo] 
[h] opcional  postvelar aspirada sorda 
[ø] no hay sonido 
Ej. mismo [mi­mo] 
Contraste con el inglés: 
El símbolo ortográfico “z” en inglés se pronuncia [z] pero en español se pronuncia [s] 
Practicar: 
president 
residencia 
presente 
reservación 
físico 
razón 
zapato 
imposición 
El zapato de Celina esta en Venezuela 
/x/­ velar fricativa sorda 
Ej. jamás [xa­más] 
gente [xén̪­te] 
Práctica de transcripcion fonética: 
El se refiere a un lugar donde un río negro se encuentra en confluencia con el ancho mar. 
[él­se­re­fié­ɾe­au̯n­lu­ɣáɾ­ðon̪­deu̯n­rí­o­né­ɣɾo­seŋ­ku̯én̪­tɾa­eŋ­koɱ­flu̯én­si̯a­ko­ne­lán­tʃo­máɾ] 
Es el mejor ejemplo de este ejercicio. 
[é­sel­me­xó­ɾe­xém­plo­ðés­te­xer­sí­si̯o] 
[é­sel­me­xó­ɾe­xém­plo­ðés­te­xer­θí­θi̯o] (para el 5% de hispanohablantes) 
**********
https://uncc.instructure.com/courses/44379/pages/clase-no-26-de-30-apuntes-de-clase-kiarra-balom-2a-vez?module_item_id=774925 1/1 
7/21/2018 Clase No. 27 de 30. Apuntes de clase. Kelli James (2a vez): 201710-Spring 2017-SPAN-4231-001:SPAN-5050-001_Combined 
Clase No. 27 de 30. Apuntes de clase. Kelli James (2a vez) 
Clase No. 27 de 30 
miércoles, 19 de abril de 2017 
SPAN 4231 / 5050: Introducción a la fonética española 
Apuntes de Kelli James (2a vez) 
(Revisados por la profesora) 
1. Repaso las instrucciones de Trabajo No. 4 (https://uncc.instructure.com/courses/44379/pages/trabajo­no­4­de­5­instrucciones­primavera­2017) 2. Transcribir Fonéticamente  
Esas yantas resbalan si hay hielo 
[é­sas­ʝan̪­tas­res­ba­lan­si̯ai̯­ʝe­lo] 
                  o [ø­rez­βa­lan] 
3. /ʝ/­ [ʝ] palatal fricativa sonora 
                  ex. llamar        yo 
                      [ʝa­már]     [ʝo] 
         [dʒ] alveopalatal africada sonora  
                  ex. cónyuge  
                       [kóɳ­dʒu­xe] 
3. El pintor salió del teatro sin Raúl 
    (no tuvimos tiempo de terminar; continuaremos con esta oración en la próxima clase) 
***************
https://uncc.instructure.com/courses/44379/pages/clase-no-27-de-30-apuntes-de-clase-kelli-james-2a-vez?module_it
